import { adminAction } from "@/app/admin/(protected)/actions";
import { AdminFormDialog } from "@/components/admin/admin-form-dialog";
import { AdminPage, Check, Field, Notice, SaveBar, SelectField } from "@/components/admin/admin-ui";
import { siteConfig } from "@/config/site";
import { formatMoney, formatMoneyInput } from "@/lib/orders";
import { formatZurichDateTimeLocal } from "@/lib/zurich-time";
import { getPromosAdminData } from "@/server/services/admin";

type Promo = Awaited<ReturnType<typeof getPromosAdminData>>[number];

export default async function PromosPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [promos, feedback] = await Promise.all([getPromosAdminData(), searchParams]);
  const returnTo = "/admin/promos";
  return <AdminPage title="Promo codes" description="Discounts applied to item subtotal only." actions={<AdminFormDialog trigger="Add promo" title="Add promo" description={`Create a fixed ${siteConfig.currency} or percentage discount.`} variant="primary"><PromoForm returnTo={returnTo} /></AdminFormDialog>}><Notice {...feedback} /><div className="overflow-hidden rounded-xl border bg-white">{promos.length === 0 ? <p className="p-8 text-center text-sm text-muted">No promo codes.</p> : promos.map((promo) => <div key={promo.id} className="flex flex-wrap items-center justify-between gap-4 border-b p-4 last:border-0"><div><h2 className="font-mono font-bold">{promo.code}</h2><p className="text-xs text-muted">{promo.type === "PERCENT" ? `${promo.value / 100}%` : formatMoney(promo.value, "en")} · minimum {formatMoney(promo.minimumSubtotalRappen, "en")} · {promo._count.redemptions} uses</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-3 py-1 text-xs font-bold ${promo.active ? "bg-emerald-50 text-emerald-800" : "bg-background text-muted"}`}>{promo.active ? "Active" : "Inactive"}</span><AdminFormDialog trigger="Edit" title={`Edit ${promo.code}`} description="Update this promo code."><PromoForm returnTo={returnTo} promo={promo} /></AdminFormDialog></div></div>)}</div></AdminPage>;
}

function PromoForm({ returnTo, promo }: { returnTo: string; promo?: Promo }) { return <form action={adminAction} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="intent" value="promo" />{promo && <input type="hidden" name="id" value={promo.id} />}<Field label="Code" name="code" defaultValue={promo?.code ?? ""} required /><SelectField label="Type" name="type" defaultValue={promo?.type ?? "FIXED"}><option value="FIXED">Fixed {siteConfig.currency}</option><option value="PERCENT">Percentage</option></SelectField><Field label={`Value (${siteConfig.currency} or %)`} name="value" type="number" min="0.01" step="0.01" defaultValue={promo ? promo.type === "PERCENT" ? (promo.value / 100).toFixed(2) : formatMoneyInput(promo.value) : ""} required /><Field label={`Minimum subtotal (${siteConfig.currency})`} name="minimumSubtotalRappen" type="number" min="0" step="0.01" defaultValue={promo ? formatMoneyInput(promo.minimumSubtotalRappen) : "0.00"} required /><Field label="Starts at (Zurich)" name="startsAt" type="datetime-local" defaultValue={promo?.startsAt ? formatZurichDateTimeLocal(promo.startsAt) : ""} /><Field label="Ends at (Zurich)" name="endsAt" type="datetime-local" defaultValue={promo?.endsAt ? formatZurichDateTimeLocal(promo.endsAt) : ""} /><Field label="Total use limit" name="totalUsageLimit" type="number" min="1" defaultValue={promo?.totalUsageLimit ?? ""} /><Field label="Per-customer limit" name="perCustomerLimit" type="number" min="1" defaultValue={promo?.perCustomerLimit ?? ""} /><Check label="Active" name="active" defaultChecked={promo?.active ?? true} /><div className="sm:col-span-2"><SaveBar returnTo={returnTo} label={promo ? "Save promo" : "Add promo"} /></div></form>; }
