import { notFound } from "next/navigation";

import { adminAction } from "@/app/admin/(protected)/actions";
import { AdminFormDialog } from "@/components/admin/admin-form-dialog";
import { AdminPage, Check, Field, Notice, SaveBar, SelectField, TextareaField } from "@/components/admin/admin-ui";
import { DeleteDialog } from "@/components/admin/danger-actions";
import { ImageUploadField } from "@/components/admin/image-upload-field";
import { SlugField } from "@/components/admin/slug-field";
import { Card } from "@/components/ui/card";
import { formatChf, formatChfInput, formatMinuteOfDay } from "@/lib/orders";
import { getMenuAdminData } from "@/server/services/admin";
import { resolvePublicImageUrl } from "@/server/storage/s3";

const weekdays = ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"];

export default async function ProductPage({ params, searchParams }: { params: Promise<{ productId: string }>; searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [{ productId }, feedback, data] = await Promise.all([params, searchParams, getMenuAdminData()]);
  const product = data.products.find((item) => item.id === productId);
  if (!product) notFound();
  const returnTo = `/admin/menu/products/${product.id}`;
  const selectedAllergens = new Set(product.allergens.map((item) => item.allergenId));
  const configuredVariantIds = new Set(product.suggestions.map((item) => item.suggestedVariantId));
  const suggestionCandidates = data.products.flatMap((candidate) => {
    if (candidate.id === product.id || candidate.optionGroups.some((group) => group.active && group.minimumSelections > 0)) return [];
    return candidate.variants.filter((variant) => variant.active && !configuredVariantIds.has(variant.id)).map((variant) => ({
      id: variant.id,
      label: `${candidate.nameEn} · ${variant.nameEn} · ${formatChf(variant.priceRappen, "en")} · ${candidate.active ? "Published" : "Draft"} · ${candidate.available ? "Available" : "Sold out"}`,
    }));
  });
  return <AdminPage title={product.nameEn} description="Compact product, pricing, options, allergens, and availability management." actions={<AdminFormDialog trigger="Edit product" title="Edit product" description="Update the product details and publication settings." variant="primary"><form action={adminAction} className="space-y-4"><input type="hidden" name="intent" value="product" /><input type="hidden" name="id" value={product.id} /><div className="grid gap-4 sm:grid-cols-2"><SelectField label="Category" name="categoryId" defaultValue={product.categoryId}>{data.categories.map((category) => <option key={category.id} value={category.id}>{category.nameEn}</option>)}</SelectField><SlugField defaultValue={product.slug} /></div><div className="grid gap-4 sm:grid-cols-2"><Field label="German name" name="nameDe" defaultValue={product.nameDe} required /><Field label="English name" name="nameEn" defaultValue={product.nameEn} required /></div><TextareaField label="German description" name="descriptionDe" defaultValue={product.descriptionDe} /><TextareaField label="English description" name="descriptionEn" defaultValue={product.descriptionEn} /><ImageUploadField initialKey={product.imageKey ?? ""} initialUrl={resolvePublicImageUrl(product.imageKey)} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Sort order" name="sortOrder" type="number" min="0" defaultValue={product.sortOrder} required /><SelectField label="Spice level" name="spiceLevel" defaultValue={product.spiceLevel ?? ""}><option value="">None</option><option value="MILD">Mild</option><option value="MEDIUM">Medium</option><option value="HOT">Hot</option><option value="EXTRA_HOT">Extra hot</option></SelectField></div><div className="flex flex-wrap gap-5"><Check label="Published" name="active" defaultChecked={product.active} /><Check label="Available" name="available" defaultChecked={product.available} /><Check label="Halal" name="isHalal" defaultChecked={product.isHalal} /><Check label="Vegetarian" name="isVegetarian" defaultChecked={product.isVegetarian} /><Check label="Vegan" name="isVegan" defaultChecked={product.isVegan} /></div><fieldset><legend className="text-sm font-semibold">Allergens</legend><div className="mt-2 flex flex-wrap gap-4">{data.allergens.map((allergen) => <label key={allergen.id} className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" name="allergen-checkbox" value={allergen.id} defaultChecked={selectedAllergens.has(allergen.id)} className="size-5 accent-primary" />{allergen.nameEn}</label>)}</div></fieldset><SaveBar returnTo={returnTo} /></form></AdminFormDialog>}>
    <Notice {...feedback} />
    <Card className="flex flex-wrap items-center justify-between gap-4 p-4"><div><p className="font-semibold">{product.nameDe}</p><p className="text-sm text-muted">/{product.slug} · {product.category.nameEn}</p></div><div className="flex gap-2 text-xs font-semibold"><span className="rounded-full bg-background px-3 py-1">{product.active ? "Published" : "Draft"}</span><span className={`rounded-full px-3 py-1 ${product.available ? "bg-emerald-50 text-emerald-800" : "bg-red-50 text-destructive"}`}>{product.available ? "Available" : "Sold out"}</span></div></Card>

    <Section title="Variants and prices" action={<AdminFormDialog trigger="Add variant" title="Add variant" description="Prices are entered as normal CHF amounts." variant="primary"><VariantForm productId={product.id} returnTo={returnTo} /></AdminFormDialog>}>
      {product.variants.length === 0 ? <p className="p-4 text-sm text-muted">No variants.</p> : product.variants.map((variant) => <Row key={variant.id} title={variant.nameEn} meta={`${formatChf(variant.priceRappen, "en")} · ${variant.active ? "Active" : "Inactive"}`} actions={<><AdminFormDialog trigger="Edit" title={`Edit ${variant.nameEn}`} description="Update this variant."><VariantForm productId={product.id} returnTo={returnTo} variant={variant} /></AdminFormDialog><DeleteDialog intent="delete_menu" kind="variant" id={variant.id} returnTo={returnTo} label="Delete" /></>}/>) }
    </Section>

    <Section title="Option groups" action={<AdminFormDialog trigger="Add group" title="Add option group" description="Set the allowed number of selections." variant="primary"><GroupForm productId={product.id} returnTo={returnTo} /></AdminFormDialog>}>
      {product.optionGroups.length === 0 ? <p className="p-4 text-sm text-muted">No option groups.</p> : product.optionGroups.map((group) => <div key={group.id} className="border-b p-4 last:border-0"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">{group.nameEn}</h3><p className="text-xs text-muted">{group.minimumSelections}–{group.maximumSelections} selections · {group.minimumSelections > 0 ? "Required" : "Optional"}</p></div><div className="flex flex-wrap gap-2"><AdminFormDialog trigger="Edit" title={`Edit ${group.nameEn}`} description="Update this option group."><GroupForm productId={product.id} returnTo={returnTo} group={group} /></AdminFormDialog><AdminFormDialog trigger="Add choice" title={`Add choice to ${group.nameEn}`} description="Enter any extra price as CHF."><ChoiceForm groupId={group.id} returnTo={returnTo} /></AdminFormDialog><DeleteDialog intent="delete_menu" kind="optionGroup" id={group.id} returnTo={returnTo} label="Delete" /></div></div><div className="mt-3 divide-y rounded-lg border bg-background">{group.choices.length === 0 ? <p className="p-3 text-xs text-muted">No choices.</p> : group.choices.map((choice) => <div key={choice.id} className="flex flex-wrap items-center justify-between gap-2 p-3"><span className="text-sm font-medium">{choice.nameEn} <small className="text-muted">+ {formatChf(choice.priceDeltaRappen, "en")}</small></span><div className="flex flex-wrap gap-2"><AdminFormDialog trigger="Edit" title={`Edit ${choice.nameEn}`} description="Update this option choice."><ChoiceForm groupId={group.id} returnTo={returnTo} choice={choice} /></AdminFormDialog><span className="ml-2 border-l pl-2"><DeleteDialog intent="delete_menu" kind="optionChoice" id={choice.id} returnTo={returnTo} label="Delete" /></span></div></div>)}</div></div>)}
    </Section>

    <Section title="People also order" action={suggestionCandidates.length > 0 ? <AdminFormDialog trigger="Add suggestion" title="Add suggested item" description="Pin one exact variant to offer with this product." variant="primary"><SuggestionForm productId={product.id} returnTo={returnTo} candidates={suggestionCandidates} /></AdminFormDialog> : null}>
      {product.suggestions.length === 0 ? <p className="p-4 text-sm text-muted">No suggested items.</p> : product.suggestions.map((suggestion) => <Row key={suggestion.id} title={`${suggestion.suggestedVariant.product.nameEn} · ${suggestion.suggestedVariant.nameEn}`} meta={`${formatChf(suggestion.suggestedVariant.priceRappen, "en")} · sort ${suggestion.sortOrder} · ${suggestion.suggestedVariant.product.active ? "Published" : "Draft"} · ${suggestion.suggestedVariant.product.available ? "Available" : "Sold out"} · ${suggestion.suggestedVariant.active ? "Active variant" : "Inactive variant"}`} actions={<><AdminFormDialog trigger="Edit order" title={`Edit ${suggestion.suggestedVariant.product.nameEn}`} description="Change where this item appears in the suggestion list."><SuggestionForm productId={product.id} returnTo={returnTo} candidates={[]} suggestion={suggestion} /></AdminFormDialog><span className="ml-2 border-l pl-2"><DeleteDialog intent="delete_product_suggestion" id={suggestion.id} returnTo={returnTo} label="Remove" description="This removes the item from this product's suggestion list." /></span></>}/>) }
    </Section>

    <Section title="Availability windows" action={<AdminFormDialog trigger="Add window" title="Add availability window" description="Leave this list empty to follow restaurant service hours." variant="primary"><WindowForm productId={product.id} returnTo={returnTo} /></AdminFormDialog>}>
      {product.availabilityWindows.length === 0 ? <p className="p-4 text-sm text-muted">Uses restaurant service hours.</p> : product.availabilityWindows.map((window) => <Row key={window.id} title={window.weekday} meta={`${formatMinuteOfDay(window.startMinute)}–${formatMinuteOfDay(window.endMinute)}`} actions={<DeleteDialog intent="delete_availability_window" id={window.id} returnTo={returnTo} label="Remove" />}/>) }
    </Section>

    <section className="mt-8 rounded-xl border border-destructive/30 bg-white p-5"><h2 className="font-display text-lg font-bold text-destructive">Danger zone</h2><div className="mt-4"><DeleteDialog intent="delete_menu" kind="product" id={product.id} returnTo="/admin/menu/products" label="Delete product" /></div></section>
  </AdminPage>;
}

function Section({ title, action, children }: { title: string; action: React.ReactNode; children: React.ReactNode }) { return <section className="mt-7"><div className="mb-3 flex items-center justify-between gap-3"><h2 className="font-display text-xl font-bold">{title}</h2>{action}</div><div className="overflow-hidden rounded-xl border bg-white">{children}</div></section>; }
function Row({ title, meta, actions }: { title: string; meta: string; actions: React.ReactNode }) { return <div className="flex flex-wrap items-center justify-between gap-3 border-b p-4 last:border-0"><div><h3 className="font-semibold">{title}</h3><p className="text-xs text-muted">{meta}</p></div><div className="flex flex-wrap gap-2">{actions}</div></div>; }

type Variant = Awaited<ReturnType<typeof getMenuAdminData>>["products"][number]["variants"][number];
function VariantForm({ productId, returnTo, variant }: { productId: string; returnTo: string; variant?: Variant }) { return <form action={adminAction} className="space-y-4"><input type="hidden" name="intent" value="variant" />{variant && <input type="hidden" name="id" value={variant.id} />}<input type="hidden" name="productId" value={productId} /><div className="grid gap-4 sm:grid-cols-2"><Field label="German name" name="nameDe" defaultValue={variant?.nameDe} required /><Field label="English name" name="nameEn" defaultValue={variant?.nameEn} required /></div><div className="grid gap-4 sm:grid-cols-3"><Field label="SKU" name="sku" defaultValue={variant?.sku ?? ""} /><Field label="Price (CHF)" name="priceRappen" type="number" min="0" step="0.01" defaultValue={variant ? formatChfInput(variant.priceRappen) : ""} required /><Field label="Sort" name="sortOrder" type="number" min="0" defaultValue={variant?.sortOrder ?? 0} required /></div><Check label="Active" name="active" defaultChecked={variant?.active ?? true} /><SaveBar returnTo={returnTo} label={variant ? "Save variant" : "Add variant"} /></form>; }
type Group = Awaited<ReturnType<typeof getMenuAdminData>>["products"][number]["optionGroups"][number];
function GroupForm({ productId, returnTo, group }: { productId: string; returnTo: string; group?: Group }) { return <form action={adminAction} className="space-y-4"><input type="hidden" name="intent" value="option_group" />{group && <input type="hidden" name="id" value={group.id} />}<input type="hidden" name="productId" value={productId} /><div className="grid gap-4 sm:grid-cols-2"><Field label="German name" name="nameDe" defaultValue={group?.nameDe} required /><Field label="English name" name="nameEn" defaultValue={group?.nameEn} required /></div><div className="grid gap-4 sm:grid-cols-3"><Field label="Minimum" name="minimumSelections" type="number" min="0" defaultValue={group?.minimumSelections ?? 0} required /><Field label="Maximum" name="maximumSelections" type="number" min="1" defaultValue={group?.maximumSelections ?? 1} required /><Field label="Sort" name="sortOrder" type="number" min="0" defaultValue={group?.sortOrder ?? 0} required /></div><p className="text-xs text-muted">Minimum 1 or more makes this group required. Add its choices before activating it on a published product.</p><Check label="Active" name="active" defaultChecked={group?.active ?? false} /><SaveBar returnTo={returnTo} label={group ? "Save group" : "Add group"} /></form>; }
type Choice = Group["choices"][number];
function ChoiceForm({ groupId, returnTo, choice }: { groupId: string; returnTo: string; choice?: Choice }) { return <form action={adminAction} className="space-y-4"><input type="hidden" name="intent" value="option_choice" />{choice && <input type="hidden" name="id" value={choice.id} />}<input type="hidden" name="optionGroupId" value={groupId} /><div className="grid gap-4 sm:grid-cols-2"><Field label="German name" name="nameDe" defaultValue={choice?.nameDe} required /><Field label="English name" name="nameEn" defaultValue={choice?.nameEn} required /></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Price adjustment (CHF)" name="priceDeltaRappen" type="number" min="0" step="0.01" defaultValue={choice ? formatChfInput(choice.priceDeltaRappen) : "0.00"} required /><Field label="Sort" name="sortOrder" type="number" min="0" defaultValue={choice?.sortOrder ?? 0} required /></div><Check label="Active" name="active" defaultChecked={choice?.active ?? true} /><SaveBar returnTo={returnTo} label={choice ? "Save choice" : "Add choice"} /></form>; }
type Suggestion = Awaited<ReturnType<typeof getMenuAdminData>>["products"][number]["suggestions"][number];
function SuggestionForm({ productId, returnTo, candidates, suggestion }: { productId: string; returnTo: string; candidates: { id: string; label: string }[]; suggestion?: Suggestion }) { return <form action={adminAction} className="space-y-4"><input type="hidden" name="intent" value="product_suggestion" />{suggestion && <input type="hidden" name="id" value={suggestion.id} />}<input type="hidden" name="productId" value={productId} />{suggestion ? <><input type="hidden" name="suggestedVariantId" value={suggestion.suggestedVariantId} /><p className="rounded-lg border bg-background p-3 text-sm font-medium">{suggestion.suggestedVariant.product.nameEn} · {suggestion.suggestedVariant.nameEn}</p></> : <SelectField label="Suggested product variant" name="suggestedVariantId">{candidates.map((candidate) => <option key={candidate.id} value={candidate.id}>{candidate.label}</option>)}</SelectField>}<Field label="Sort order" name="sortOrder" type="number" min="0" defaultValue={suggestion?.sortOrder ?? 0} required /><SaveBar returnTo={returnTo} label={suggestion ? "Save order" : "Add suggestion"} /></form>; }
function WindowForm({ productId, returnTo }: { productId: string; returnTo: string }) { return <form action={adminAction} className="space-y-4"><input type="hidden" name="intent" value="availability_window" /><input type="hidden" name="productId" value={productId} /><SelectField label="Weekday" name="weekday">{weekdays.map((day) => <option key={day}>{day}</option>)}</SelectField><div className="grid gap-4 sm:grid-cols-2"><Field label="Start" name="startMinute" type="time" required /><Field label="End" name="endMinute" type="time" required /></div><SaveBar returnTo={returnTo} label="Add window" /></form>; }
