import { adminAction } from "@/app/admin/(protected)/actions";
import { AdminFormDialog } from "@/components/admin/admin-form-dialog";
import { AdminPage, Check, Field, Notice, SaveBar } from "@/components/admin/admin-ui";
import { DeleteDialog } from "@/components/admin/danger-actions";
import { Button } from "@/components/ui/button";
import { formatChf, formatChfInput } from "@/lib/orders";
import { getSettingsAdminData } from "@/server/services/admin";

type Zone = Awaited<ReturnType<typeof getSettingsAdminData>>["zones"][number];

export default async function ZonesPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [{ zones }, feedback] = await Promise.all([getSettingsAdminData(), searchParams]);
  const returnTo = "/admin/settings/delivery-zones";
  return <AdminPage title="Delivery zones" description="Swiss postcodes, fees, minimums, and delivery estimates." actions={<AdminFormDialog trigger="Add zone" title="Add delivery zone" description="Configure a Swiss delivery area." variant="primary"><ZoneForm returnTo={returnTo} /></AdminFormDialog>}><Notice {...feedback} /><div className="space-y-4">{zones.length === 0 ? <p className="rounded-xl border bg-white p-8 text-center text-sm text-muted">No delivery zones.</p> : zones.map((zone) => <section key={zone.id} className="overflow-hidden rounded-xl border bg-white"><div className="flex flex-wrap items-center justify-between gap-4 p-4"><div><h2 className="font-semibold">{zone.nameEn}</h2><p className="text-xs text-muted">{formatChf(zone.feeRappen, "en")} fee · {formatChf(zone.minimumSubtotalRappen, "en")} minimum · about {zone.estimatedMinutes} min</p></div><div className="flex items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-bold ${zone.active ? "bg-emerald-50 text-emerald-800" : "bg-background text-muted"}`}>{zone.active ? "Active" : "Inactive"}</span><AdminFormDialog trigger="Edit" title={`Edit ${zone.nameEn}`} description="Update zone pricing and timing."><ZoneForm returnTo={returnTo} zone={zone} /></AdminFormDialog></div></div><div className="border-t bg-background/50 p-4"><div className="flex flex-wrap gap-2">{zone.postalCodes.map((postcode) => <span key={postcode.id} className="inline-flex items-center gap-1 rounded-lg border bg-white pl-3 text-sm font-semibold">{postcode.postalCode}<DeleteDialog intent="delete_postal_code" id={postcode.id} returnTo={returnTo} label="Remove" description={`Remove postcode ${postcode.postalCode} from this delivery zone?`} /></span>)}</div><form action={adminAction} className="mt-3 flex flex-wrap items-end gap-2"><input type="hidden" name="intent" value="postal_code" /><input type="hidden" name="deliveryZoneId" value={zone.id} /><Field label="Add Swiss postcode" name="postalCode" inputMode="numeric" pattern="[0-9]{4}" required /><input type="hidden" name="returnTo" value={returnTo} /><Button type="submit">Add postcode</Button></form></div></section>)}</div></AdminPage>;
}

function ZoneForm({ returnTo, zone }: { returnTo: string; zone?: Zone }) { return <form action={adminAction} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="intent" value="zone" />{zone && <input type="hidden" name="id" value={zone.id} />}<Field label="German name" name="nameDe" defaultValue={zone?.nameDe} required /><Field label="English name" name="nameEn" defaultValue={zone?.nameEn} required /><Field label="Delivery fee (CHF)" name="feeRappen" type="number" min="0" step="0.01" defaultValue={zone ? formatChfInput(zone.feeRappen) : ""} required /><Field label="Minimum subtotal (CHF)" name="minimumSubtotalRappen" type="number" min="0" step="0.01" defaultValue={zone ? formatChfInput(zone.minimumSubtotalRappen) : "0.00"} required /><Field label="Free delivery threshold (CHF)" name="freeDeliveryThresholdRappen" type="number" min="0" step="0.01" defaultValue={zone?.freeDeliveryThresholdRappen == null ? "" : formatChfInput(zone.freeDeliveryThresholdRappen)} /><Field label="Estimated minutes" name="estimatedMinutes" type="number" min="1" defaultValue={zone?.estimatedMinutes} required /><Field label="Sort" name="sortOrder" type="number" min="0" defaultValue={zone?.sortOrder ?? 0} required /><Check label="Active" name="active" defaultChecked={zone?.active ?? true} /><div className="sm:col-span-2"><SaveBar returnTo={returnTo} label={zone ? "Save zone" : "Add zone"} /></div></form>; }
