import { adminAction } from "@/app/admin/(protected)/actions";
import { AdminFormDialog } from "@/components/admin/admin-form-dialog";
import { AdminPage, Check, Field, Notice, SaveBar, SelectField, TextareaField } from "@/components/admin/admin-ui";
import { DeleteDialog } from "@/components/admin/danger-actions";
import { Card } from "@/components/ui/card";
import { formatMinuteOfDay } from "@/lib/orders";
import { getSettingsAdminData } from "@/server/services/admin";

const weekdays = ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"];
const types = ["DELIVERY", "PICKUP"];

export default async function HoursPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [{ fulfillment, windows, exceptions }, feedback] = await Promise.all([getSettingsAdminData(), searchParams]);
  const returnTo = "/admin/settings/hours";
  return <AdminPage title="Hours and availability" description="Fulfilment settings, weekly service windows, and one-off exceptions.">
    <Notice {...feedback} />
    <Card className="p-5"><h2 className="font-display text-lg font-semibold">Fulfilment</h2><form action={adminAction} className="mt-4 space-y-4"><input type="hidden" name="intent" value="fulfillment" /><div className="flex flex-wrap gap-5"><Check label="Delivery" name="deliveryEnabled" defaultChecked={fulfillment.deliveryEnabled} /><Check label="Pickup" name="pickupEnabled" defaultChecked={fulfillment.pickupEnabled} /><Check label="ASAP" name="asapEnabled" defaultChecked={fulfillment.asapEnabled} /><Check label="Scheduled" name="scheduledEnabled" defaultChecked={fulfillment.scheduledEnabled} /></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Delivery prep minutes" name="deliveryPrepMinutes" type="number" min="1" defaultValue={fulfillment.deliveryPrepMinutes} required /><Field label="Pickup prep minutes" name="pickupPrepMinutes" type="number" min="1" defaultValue={fulfillment.pickupPrepMinutes} required /><Field label="Minimum lead minutes" name="minimumLeadMinutes" type="number" min="0" defaultValue={fulfillment.minimumLeadMinutes} required /><Field label="Maximum advance days" name="maximumAdvanceDays" type="number" min="1" defaultValue={fulfillment.maximumAdvanceDays} required /><Field label="Slot interval minutes" name="slotIntervalMinutes" type="number" min="1" defaultValue={fulfillment.slotIntervalMinutes} required /><Field label="Default slot capacity" name="defaultSlotCapacity" type="number" min="1" defaultValue={fulfillment.defaultSlotCapacity} required /></div><div className="grid gap-4 sm:grid-cols-2"><TextareaField label="German pickup instructions" name="pickupInstructionsDe" defaultValue={fulfillment.pickupInstructionsDe} /><TextareaField label="English pickup instructions" name="pickupInstructionsEn" defaultValue={fulfillment.pickupInstructionsEn} /></div><SaveBar returnTo={returnTo} /></form></Card>
    <section className="mt-7" aria-labelledby="weekly-hours"><div className="flex items-center justify-between gap-3"><h2 id="weekly-hours" className="font-display text-xl font-semibold">Weekly windows</h2><AdminFormDialog trigger="Add window" title="Add service window"><form action={adminAction} className="space-y-4"><input type="hidden" name="intent" value="opening_window" /><div className="grid gap-4 sm:grid-cols-2"><SelectField label="Type" name="fulfillmentType">{types.map((type) => <option key={type}>{type}</option>)}</SelectField><SelectField label="Weekday" name="weekday">{weekdays.map((day) => <option key={day}>{day}</option>)}</SelectField><Field label="Start" name="startMinute" type="time" required /><Field label="End" name="endMinute" type="time" required /><Field label="Sort order" name="sortOrder" type="number" min="0" defaultValue="0" required /><Check label="Active" name="active" defaultChecked /></div><SaveBar returnTo={returnTo} label="Add window" /></form></AdminFormDialog></div><Card className="mt-3 overflow-hidden p-0"><ul className="divide-y divide-border">{windows.map((window) => <li key={window.id} className="flex min-h-16 items-center justify-between gap-4 px-4 py-3"><p><strong className="text-sm">{window.weekday} · {window.fulfillmentType}</strong><br /><span className="text-sm text-muted">{formatMinuteOfDay(window.startMinute)}–{formatMinuteOfDay(window.endMinute)} · {window.active ? "Active" : "Inactive"}</span></p><DeleteDialog intent="delete_schedule" kind="window" id={window.id} returnTo={returnTo} label="Remove" /></li>)}</ul></Card></section>
    <section className="mt-7" aria-labelledby="exceptions"><div className="flex items-center justify-between gap-3"><h2 id="exceptions" className="font-display text-xl font-semibold">Service exceptions</h2><AdminFormDialog trigger="Add exception" title="Add service exception"><form action={adminAction} className="space-y-4"><input type="hidden" name="intent" value="service_exception" /><div className="grid gap-4 sm:grid-cols-2"><Field label="Date" name="date" type="date" required /><SelectField label="Type" name="fulfillmentType">{types.map((type) => <option key={type}>{type}</option>)}</SelectField><Check label="Closed all day" name="closed" defaultChecked /><Field label="Replacement start" name="startMinute" type="time" /><Field label="Replacement end" name="endMinute" type="time" /><Field label="Note" name="note" /></div><SaveBar returnTo={returnTo} label="Add exception" /></form></AdminFormDialog></div><Card className="mt-3 overflow-hidden p-0"><ul className="divide-y divide-border">{exceptions.map((exception) => <li key={exception.id} className="flex min-h-16 items-center justify-between gap-4 px-4 py-3"><p><strong className="text-sm">{exception.date.toISOString().slice(0, 10)} · {exception.fulfillmentType}</strong><br /><span className="text-sm text-muted">{exception.closed ? "Closed" : `${formatMinuteOfDay(exception.startMinute ?? 0)}–${formatMinuteOfDay(exception.endMinute ?? 0)}`}{exception.note ? ` · ${exception.note}` : ""}</span></p><DeleteDialog intent="delete_schedule" kind="exception" id={exception.id} returnTo={returnTo} label="Remove" /></li>)}</ul></Card></section>
  </AdminPage>;
}
