import { adminAction } from "@/app/admin/(protected)/actions";
import { AdminPage, Check, Field, Notice, SaveBar, TextareaField } from "@/components/admin/admin-ui";
import { Card } from "@/components/ui/card";
import { getSettingsAdminData } from "@/server/services/admin";

export default async function GeneralSettingsPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [{ site }, feedback] = await Promise.all([getSettingsAdminData(), searchParams]);
  const returnTo = "/admin/settings/general";
  return <AdminPage title="Site settings" description="Key public identity, contact, brand, and bilingual content."><Notice {...feedback} /><Card><form action={adminAction} className="space-y-6"><input type="hidden" name="intent" value="site_settings" /><fieldset className="grid gap-4 sm:grid-cols-2"><legend className="mb-3 font-display text-xl font-semibold sm:col-span-2">Business details</legend><Field label="Display name" name="displayName" defaultValue={site.displayName} required /><Field label="Legal name" name="legalName" defaultValue={site.legalName ?? ""} /><Field label="Email" name="email" type="email" defaultValue={site.email ?? ""} /><Field label="Phone" name="phone" type="tel" defaultValue={site.phone ?? ""} /><Field label="Street" name="street" defaultValue={site.street ?? ""} /><Field label="Postcode" name="postalCode" defaultValue={site.postalCode ?? ""} /><Field label="City" name="city" defaultValue={site.city ?? ""} /></fieldset><fieldset className="grid gap-4 sm:grid-cols-2"><legend className="mb-3 font-display text-xl font-semibold sm:col-span-2">Brand assets</legend><Field label="Primary colour" name="primaryColor" type="color" defaultValue={site.primaryColor} required /><Field label="Secondary colour" name="secondaryColor" type="color" defaultValue={site.secondaryColor} required /><Field label="Logo S3 key" name="logoKey" defaultValue={site.logoKey ?? ""} /><Field label="Compact logo S3 key" name="compactLogoKey" defaultValue={site.compactLogoKey ?? ""} /><Field label="Favicon S3 key" name="faviconKey" defaultValue={site.faviconKey ?? ""} /><Field label="Hero image S3 key" name="heroImageKey" defaultValue={site.heroImageKey ?? ""} /></fieldset><fieldset className="grid gap-4 sm:grid-cols-2"><legend className="mb-3 font-display text-xl font-semibold sm:col-span-2">Public content</legend><Field label="German hero title" name="heroTitleDe" defaultValue={site.heroTitleDe ?? ""} /><Field label="English hero title" name="heroTitleEn" defaultValue={site.heroTitleEn ?? ""} /><TextareaField label="German hero subtitle" name="heroSubtitleDe" defaultValue={site.heroSubtitleDe} /><TextareaField label="English hero subtitle" name="heroSubtitleEn" defaultValue={site.heroSubtitleEn} /><TextareaField label="German about" name="aboutDe" defaultValue={site.aboutDe} rows={6} /><TextareaField label="English about" name="aboutEn" defaultValue={site.aboutEn} rows={6} /><Field label="German announcement" name="announcementDe" defaultValue={site.announcementDe ?? ""} /><Field label="English announcement" name="announcementEn" defaultValue={site.announcementEn ?? ""} /><Check label="Show announcement" name="announcementActive" defaultChecked={site.announcementActive} /><Field label="Instagram URL" name="instagramUrl" type="url" defaultValue={site.instagramUrl ?? ""} /><Field label="Facebook URL" name="facebookUrl" type="url" defaultValue={site.facebookUrl ?? ""} /></fieldset><SaveBar returnTo={returnTo} /></form></Card></AdminPage>;
}
